// Code generated by protoc-gen-go. DO NOT EDIT.
// source: module/pb/inventory.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OnhandQTY struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Itemname             string   `protobuf:"bytes,2,opt,name=itemname,proto3" json:"itemname,omitempty"`
	Stock                int64    `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnhandQTY) Reset()         { *m = OnhandQTY{} }
func (m *OnhandQTY) String() string { return proto.CompactTextString(m) }
func (*OnhandQTY) ProtoMessage()    {}
func (*OnhandQTY) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{0}
}

func (m *OnhandQTY) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnhandQTY.Unmarshal(m, b)
}
func (m *OnhandQTY) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnhandQTY.Marshal(b, m, deterministic)
}
func (m *OnhandQTY) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnhandQTY.Merge(m, src)
}
func (m *OnhandQTY) XXX_Size() int {
	return xxx_messageInfo_OnhandQTY.Size(m)
}
func (m *OnhandQTY) XXX_DiscardUnknown() {
	xxx_messageInfo_OnhandQTY.DiscardUnknown(m)
}

var xxx_messageInfo_OnhandQTY proto.InternalMessageInfo

func (m *OnhandQTY) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *OnhandQTY) GetItemname() string {
	if m != nil {
		return m.Itemname
	}
	return ""
}

func (m *OnhandQTY) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

type Inbound struct {
	PoDate               string   `protobuf:"bytes,1,opt,name=poDate,proto3" json:"poDate,omitempty"`
	Sku                  string   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	PoLine               int64    `protobuf:"varint,3,opt,name=poLine,proto3" json:"poLine,omitempty"`
	QtyPo                int64    `protobuf:"varint,4,opt,name=qtyPo,proto3" json:"qtyPo,omitempty"`
	QtyReceive           int64    `protobuf:"varint,5,opt,name=qtyReceive,proto3" json:"qtyReceive,omitempty"`
	PurchasePrice        float32  `protobuf:"fixed32,6,opt,name=purchasePrice,proto3" json:"purchasePrice,omitempty"`
	TotalInboundPrice    float32  `protobuf:"fixed32,7,opt,name=totalInboundPrice,proto3" json:"totalInboundPrice,omitempty"`
	KwitansiNum          string   `protobuf:"bytes,8,opt,name=kwitansiNum,proto3" json:"kwitansiNum,omitempty"`
	Noted                string   `protobuf:"bytes,9,opt,name=noted,proto3" json:"noted,omitempty"`
	ItemName             string   `protobuf:"bytes,10,opt,name=itemName,proto3" json:"itemName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inbound) Reset()         { *m = Inbound{} }
func (m *Inbound) String() string { return proto.CompactTextString(m) }
func (*Inbound) ProtoMessage()    {}
func (*Inbound) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{1}
}

func (m *Inbound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inbound.Unmarshal(m, b)
}
func (m *Inbound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inbound.Marshal(b, m, deterministic)
}
func (m *Inbound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inbound.Merge(m, src)
}
func (m *Inbound) XXX_Size() int {
	return xxx_messageInfo_Inbound.Size(m)
}
func (m *Inbound) XXX_DiscardUnknown() {
	xxx_messageInfo_Inbound.DiscardUnknown(m)
}

var xxx_messageInfo_Inbound proto.InternalMessageInfo

func (m *Inbound) GetPoDate() string {
	if m != nil {
		return m.PoDate
	}
	return ""
}

func (m *Inbound) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Inbound) GetPoLine() int64 {
	if m != nil {
		return m.PoLine
	}
	return 0
}

func (m *Inbound) GetQtyPo() int64 {
	if m != nil {
		return m.QtyPo
	}
	return 0
}

func (m *Inbound) GetQtyReceive() int64 {
	if m != nil {
		return m.QtyReceive
	}
	return 0
}

func (m *Inbound) GetPurchasePrice() float32 {
	if m != nil {
		return m.PurchasePrice
	}
	return 0
}

func (m *Inbound) GetTotalInboundPrice() float32 {
	if m != nil {
		return m.TotalInboundPrice
	}
	return 0
}

func (m *Inbound) GetKwitansiNum() string {
	if m != nil {
		return m.KwitansiNum
	}
	return ""
}

func (m *Inbound) GetNoted() string {
	if m != nil {
		return m.Noted
	}
	return ""
}

func (m *Inbound) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

type Outbound struct {
	OrderDate            string   `protobuf:"bytes,1,opt,name=orderDate,proto3" json:"orderDate,omitempty"`
	Sku                  string   `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Itemname             string   `protobuf:"bytes,3,opt,name=itemname,proto3" json:"itemname,omitempty"`
	QtyOut               int64    `protobuf:"varint,4,opt,name=qtyOut,proto3" json:"qtyOut,omitempty"`
	SellingPrice         float32  `protobuf:"fixed32,5,opt,name=sellingPrice,proto3" json:"sellingPrice,omitempty"`
	TotalOutboundPrice   float32  `protobuf:"fixed32,6,opt,name=totalOutboundPrice,proto3" json:"totalOutboundPrice,omitempty"`
	Noted                string   `protobuf:"bytes,7,opt,name=noted,proto3" json:"noted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outbound) Reset()         { *m = Outbound{} }
func (m *Outbound) String() string { return proto.CompactTextString(m) }
func (*Outbound) ProtoMessage()    {}
func (*Outbound) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{2}
}

func (m *Outbound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outbound.Unmarshal(m, b)
}
func (m *Outbound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outbound.Marshal(b, m, deterministic)
}
func (m *Outbound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outbound.Merge(m, src)
}
func (m *Outbound) XXX_Size() int {
	return xxx_messageInfo_Outbound.Size(m)
}
func (m *Outbound) XXX_DiscardUnknown() {
	xxx_messageInfo_Outbound.DiscardUnknown(m)
}

var xxx_messageInfo_Outbound proto.InternalMessageInfo

func (m *Outbound) GetOrderDate() string {
	if m != nil {
		return m.OrderDate
	}
	return ""
}

func (m *Outbound) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *Outbound) GetItemname() string {
	if m != nil {
		return m.Itemname
	}
	return ""
}

func (m *Outbound) GetQtyOut() int64 {
	if m != nil {
		return m.QtyOut
	}
	return 0
}

func (m *Outbound) GetSellingPrice() float32 {
	if m != nil {
		return m.SellingPrice
	}
	return 0
}

func (m *Outbound) GetTotalOutboundPrice() float32 {
	if m != nil {
		return m.TotalOutboundPrice
	}
	return 0
}

func (m *Outbound) GetNoted() string {
	if m != nil {
		return m.Noted
	}
	return ""
}

type ReportValueHeader struct {
	CountSku             int64               `protobuf:"varint,1,opt,name=countSku,proto3" json:"countSku,omitempty"`
	SumStock             int64               `protobuf:"varint,2,opt,name=sumStock,proto3" json:"sumStock,omitempty"`
	TotalValue           float32             `protobuf:"fixed32,3,opt,name=totalValue,proto3" json:"totalValue,omitempty"`
	PrintDate            string              `protobuf:"bytes,4,opt,name=printDate,proto3" json:"printDate,omitempty"`
	ReportValueLines     []*ReportValueLines `protobuf:"bytes,5,rep,name=ReportValueLines,proto3" json:"ReportValueLines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ReportValueHeader) Reset()         { *m = ReportValueHeader{} }
func (m *ReportValueHeader) String() string { return proto.CompactTextString(m) }
func (*ReportValueHeader) ProtoMessage()    {}
func (*ReportValueHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{3}
}

func (m *ReportValueHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportValueHeader.Unmarshal(m, b)
}
func (m *ReportValueHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportValueHeader.Marshal(b, m, deterministic)
}
func (m *ReportValueHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportValueHeader.Merge(m, src)
}
func (m *ReportValueHeader) XXX_Size() int {
	return xxx_messageInfo_ReportValueHeader.Size(m)
}
func (m *ReportValueHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportValueHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ReportValueHeader proto.InternalMessageInfo

func (m *ReportValueHeader) GetCountSku() int64 {
	if m != nil {
		return m.CountSku
	}
	return 0
}

func (m *ReportValueHeader) GetSumStock() int64 {
	if m != nil {
		return m.SumStock
	}
	return 0
}

func (m *ReportValueHeader) GetTotalValue() float32 {
	if m != nil {
		return m.TotalValue
	}
	return 0
}

func (m *ReportValueHeader) GetPrintDate() string {
	if m != nil {
		return m.PrintDate
	}
	return ""
}

func (m *ReportValueHeader) GetReportValueLines() []*ReportValueLines {
	if m != nil {
		return m.ReportValueLines
	}
	return nil
}

type ReportValueLines struct {
	Sku                  string   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Itemname             string   `protobuf:"bytes,2,opt,name=itemname,proto3" json:"itemname,omitempty"`
	QtyTotalInv          int64    `protobuf:"varint,3,opt,name=qtyTotalInv,proto3" json:"qtyTotalInv,omitempty"`
	AvgPruchasePrice     float32  `protobuf:"fixed32,4,opt,name=avgPruchasePrice,proto3" json:"avgPruchasePrice,omitempty"`
	TotalPurchasePrice   float32  `protobuf:"fixed32,5,opt,name=totalPurchasePrice,proto3" json:"totalPurchasePrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportValueLines) Reset()         { *m = ReportValueLines{} }
func (m *ReportValueLines) String() string { return proto.CompactTextString(m) }
func (*ReportValueLines) ProtoMessage()    {}
func (*ReportValueLines) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{4}
}

func (m *ReportValueLines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportValueLines.Unmarshal(m, b)
}
func (m *ReportValueLines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportValueLines.Marshal(b, m, deterministic)
}
func (m *ReportValueLines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportValueLines.Merge(m, src)
}
func (m *ReportValueLines) XXX_Size() int {
	return xxx_messageInfo_ReportValueLines.Size(m)
}
func (m *ReportValueLines) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportValueLines.DiscardUnknown(m)
}

var xxx_messageInfo_ReportValueLines proto.InternalMessageInfo

func (m *ReportValueLines) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *ReportValueLines) GetItemname() string {
	if m != nil {
		return m.Itemname
	}
	return ""
}

func (m *ReportValueLines) GetQtyTotalInv() int64 {
	if m != nil {
		return m.QtyTotalInv
	}
	return 0
}

func (m *ReportValueLines) GetAvgPruchasePrice() float32 {
	if m != nil {
		return m.AvgPruchasePrice
	}
	return 0
}

func (m *ReportValueLines) GetTotalPurchasePrice() float32 {
	if m != nil {
		return m.TotalPurchasePrice
	}
	return 0
}

type ReportSalesHeader struct {
	PrintDate            string              `protobuf:"bytes,1,opt,name=printDate,proto3" json:"printDate,omitempty"`
	ParamDate            string              `protobuf:"bytes,2,opt,name=paramDate,proto3" json:"paramDate,omitempty"`
	TotalOmset           float32             `protobuf:"fixed32,3,opt,name=totalOmset,proto3" json:"totalOmset,omitempty"`
	TotalLabaGross       float32             `protobuf:"fixed32,4,opt,name=totalLabaGross,proto3" json:"totalLabaGross,omitempty"`
	TotalPenjualan       int64               `protobuf:"varint,5,opt,name=totalPenjualan,proto3" json:"totalPenjualan,omitempty"`
	TotalBarang          int64               `protobuf:"varint,6,opt,name=totalBarang,proto3" json:"totalBarang,omitempty"`
	ReportSalesLines     []*ReportSalesLines `protobuf:"bytes,7,rep,name=ReportSalesLines,proto3" json:"ReportSalesLines,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ReportSalesHeader) Reset()         { *m = ReportSalesHeader{} }
func (m *ReportSalesHeader) String() string { return proto.CompactTextString(m) }
func (*ReportSalesHeader) ProtoMessage()    {}
func (*ReportSalesHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{5}
}

func (m *ReportSalesHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportSalesHeader.Unmarshal(m, b)
}
func (m *ReportSalesHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportSalesHeader.Marshal(b, m, deterministic)
}
func (m *ReportSalesHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportSalesHeader.Merge(m, src)
}
func (m *ReportSalesHeader) XXX_Size() int {
	return xxx_messageInfo_ReportSalesHeader.Size(m)
}
func (m *ReportSalesHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportSalesHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ReportSalesHeader proto.InternalMessageInfo

func (m *ReportSalesHeader) GetPrintDate() string {
	if m != nil {
		return m.PrintDate
	}
	return ""
}

func (m *ReportSalesHeader) GetParamDate() string {
	if m != nil {
		return m.ParamDate
	}
	return ""
}

func (m *ReportSalesHeader) GetTotalOmset() float32 {
	if m != nil {
		return m.TotalOmset
	}
	return 0
}

func (m *ReportSalesHeader) GetTotalLabaGross() float32 {
	if m != nil {
		return m.TotalLabaGross
	}
	return 0
}

func (m *ReportSalesHeader) GetTotalPenjualan() int64 {
	if m != nil {
		return m.TotalPenjualan
	}
	return 0
}

func (m *ReportSalesHeader) GetTotalBarang() int64 {
	if m != nil {
		return m.TotalBarang
	}
	return 0
}

func (m *ReportSalesHeader) GetReportSalesLines() []*ReportSalesLines {
	if m != nil {
		return m.ReportSalesLines
	}
	return nil
}

type ReportSalesLines struct {
	OrderNum             string   `protobuf:"bytes,1,opt,name=orderNum,proto3" json:"orderNum,omitempty"`
	OrderDate            string   `protobuf:"bytes,2,opt,name=orderDate,proto3" json:"orderDate,omitempty"`
	Sku                  string   `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	ItemName             string   `protobuf:"bytes,4,opt,name=itemName,proto3" json:"itemName,omitempty"`
	QtySo                int64    `protobuf:"varint,5,opt,name=qtySo,proto3" json:"qtySo,omitempty"`
	SellingPrice         float32  `protobuf:"fixed32,6,opt,name=sellingPrice,proto3" json:"sellingPrice,omitempty"`
	TotalPrice           float32  `protobuf:"fixed32,7,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	PurchasePrice        float32  `protobuf:"fixed32,8,opt,name=purchasePrice,proto3" json:"purchasePrice,omitempty"`
	Laba                 float32  `protobuf:"fixed32,9,opt,name=laba,proto3" json:"laba,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportSalesLines) Reset()         { *m = ReportSalesLines{} }
func (m *ReportSalesLines) String() string { return proto.CompactTextString(m) }
func (*ReportSalesLines) ProtoMessage()    {}
func (*ReportSalesLines) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{6}
}

func (m *ReportSalesLines) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportSalesLines.Unmarshal(m, b)
}
func (m *ReportSalesLines) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportSalesLines.Marshal(b, m, deterministic)
}
func (m *ReportSalesLines) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportSalesLines.Merge(m, src)
}
func (m *ReportSalesLines) XXX_Size() int {
	return xxx_messageInfo_ReportSalesLines.Size(m)
}
func (m *ReportSalesLines) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportSalesLines.DiscardUnknown(m)
}

var xxx_messageInfo_ReportSalesLines proto.InternalMessageInfo

func (m *ReportSalesLines) GetOrderNum() string {
	if m != nil {
		return m.OrderNum
	}
	return ""
}

func (m *ReportSalesLines) GetOrderDate() string {
	if m != nil {
		return m.OrderDate
	}
	return ""
}

func (m *ReportSalesLines) GetSku() string {
	if m != nil {
		return m.Sku
	}
	return ""
}

func (m *ReportSalesLines) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

func (m *ReportSalesLines) GetQtySo() int64 {
	if m != nil {
		return m.QtySo
	}
	return 0
}

func (m *ReportSalesLines) GetSellingPrice() float32 {
	if m != nil {
		return m.SellingPrice
	}
	return 0
}

func (m *ReportSalesLines) GetTotalPrice() float32 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *ReportSalesLines) GetPurchasePrice() float32 {
	if m != nil {
		return m.PurchasePrice
	}
	return 0
}

func (m *ReportSalesLines) GetLaba() float32 {
	if m != nil {
		return m.Laba
	}
	return 0
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type ResOnhandQTY struct {
	Total                int64        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*OnhandQTY `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ResOnhandQTY) Reset()         { *m = ResOnhandQTY{} }
func (m *ResOnhandQTY) String() string { return proto.CompactTextString(m) }
func (*ResOnhandQTY) ProtoMessage()    {}
func (*ResOnhandQTY) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{8}
}

func (m *ResOnhandQTY) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResOnhandQTY.Unmarshal(m, b)
}
func (m *ResOnhandQTY) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResOnhandQTY.Marshal(b, m, deterministic)
}
func (m *ResOnhandQTY) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResOnhandQTY.Merge(m, src)
}
func (m *ResOnhandQTY) XXX_Size() int {
	return xxx_messageInfo_ResOnhandQTY.Size(m)
}
func (m *ResOnhandQTY) XXX_DiscardUnknown() {
	xxx_messageInfo_ResOnhandQTY.DiscardUnknown(m)
}

var xxx_messageInfo_ResOnhandQTY proto.InternalMessageInfo

func (m *ResOnhandQTY) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResOnhandQTY) GetData() []*OnhandQTY {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResInbounds struct {
	Total                int64      `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*Inbound `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResInbounds) Reset()         { *m = ResInbounds{} }
func (m *ResInbounds) String() string { return proto.CompactTextString(m) }
func (*ResInbounds) ProtoMessage()    {}
func (*ResInbounds) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{9}
}

func (m *ResInbounds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResInbounds.Unmarshal(m, b)
}
func (m *ResInbounds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResInbounds.Marshal(b, m, deterministic)
}
func (m *ResInbounds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResInbounds.Merge(m, src)
}
func (m *ResInbounds) XXX_Size() int {
	return xxx_messageInfo_ResInbounds.Size(m)
}
func (m *ResInbounds) XXX_DiscardUnknown() {
	xxx_messageInfo_ResInbounds.DiscardUnknown(m)
}

var xxx_messageInfo_ResInbounds proto.InternalMessageInfo

func (m *ResInbounds) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResInbounds) GetData() []*Inbound {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResOutbounds struct {
	Total                int64       `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*Outbound `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ResOutbounds) Reset()         { *m = ResOutbounds{} }
func (m *ResOutbounds) String() string { return proto.CompactTextString(m) }
func (*ResOutbounds) ProtoMessage()    {}
func (*ResOutbounds) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{10}
}

func (m *ResOutbounds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResOutbounds.Unmarshal(m, b)
}
func (m *ResOutbounds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResOutbounds.Marshal(b, m, deterministic)
}
func (m *ResOutbounds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResOutbounds.Merge(m, src)
}
func (m *ResOutbounds) XXX_Size() int {
	return xxx_messageInfo_ResOutbounds.Size(m)
}
func (m *ResOutbounds) XXX_DiscardUnknown() {
	xxx_messageInfo_ResOutbounds.DiscardUnknown(m)
}

var xxx_messageInfo_ResOutbounds proto.InternalMessageInfo

func (m *ResOutbounds) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResOutbounds) GetData() []*Outbound {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResReportValue struct {
	Total                int64                `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*ReportValueHeader `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResReportValue) Reset()         { *m = ResReportValue{} }
func (m *ResReportValue) String() string { return proto.CompactTextString(m) }
func (*ResReportValue) ProtoMessage()    {}
func (*ResReportValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{11}
}

func (m *ResReportValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResReportValue.Unmarshal(m, b)
}
func (m *ResReportValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResReportValue.Marshal(b, m, deterministic)
}
func (m *ResReportValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResReportValue.Merge(m, src)
}
func (m *ResReportValue) XXX_Size() int {
	return xxx_messageInfo_ResReportValue.Size(m)
}
func (m *ResReportValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ResReportValue.DiscardUnknown(m)
}

var xxx_messageInfo_ResReportValue proto.InternalMessageInfo

func (m *ResReportValue) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResReportValue) GetData() []*ReportValueHeader {
	if m != nil {
		return m.Data
	}
	return nil
}

type ResReportSalesHeader struct {
	Total                int64                `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*ReportSalesHeader `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResReportSalesHeader) Reset()         { *m = ResReportSalesHeader{} }
func (m *ResReportSalesHeader) String() string { return proto.CompactTextString(m) }
func (*ResReportSalesHeader) ProtoMessage()    {}
func (*ResReportSalesHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{12}
}

func (m *ResReportSalesHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResReportSalesHeader.Unmarshal(m, b)
}
func (m *ResReportSalesHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResReportSalesHeader.Marshal(b, m, deterministic)
}
func (m *ResReportSalesHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResReportSalesHeader.Merge(m, src)
}
func (m *ResReportSalesHeader) XXX_Size() int {
	return xxx_messageInfo_ResReportSalesHeader.Size(m)
}
func (m *ResReportSalesHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ResReportSalesHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ResReportSalesHeader proto.InternalMessageInfo

func (m *ResReportSalesHeader) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ResReportSalesHeader) GetData() []*ReportSalesHeader {
	if m != nil {
		return m.Data
	}
	return nil
}

type ParamDate struct {
	DateFrom             string   `protobuf:"bytes,1,opt,name=dateFrom,proto3" json:"dateFrom,omitempty"`
	DateTo               string   `protobuf:"bytes,2,opt,name=dateTo,proto3" json:"dateTo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParamDate) Reset()         { *m = ParamDate{} }
func (m *ParamDate) String() string { return proto.CompactTextString(m) }
func (*ParamDate) ProtoMessage()    {}
func (*ParamDate) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d3b5a39cf1533a, []int{13}
}

func (m *ParamDate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParamDate.Unmarshal(m, b)
}
func (m *ParamDate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParamDate.Marshal(b, m, deterministic)
}
func (m *ParamDate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParamDate.Merge(m, src)
}
func (m *ParamDate) XXX_Size() int {
	return xxx_messageInfo_ParamDate.Size(m)
}
func (m *ParamDate) XXX_DiscardUnknown() {
	xxx_messageInfo_ParamDate.DiscardUnknown(m)
}

var xxx_messageInfo_ParamDate proto.InternalMessageInfo

func (m *ParamDate) GetDateFrom() string {
	if m != nil {
		return m.DateFrom
	}
	return ""
}

func (m *ParamDate) GetDateTo() string {
	if m != nil {
		return m.DateTo
	}
	return ""
}

func init() {
	proto.RegisterType((*OnhandQTY)(nil), "pb.OnhandQTY")
	proto.RegisterType((*Inbound)(nil), "pb.Inbound")
	proto.RegisterType((*Outbound)(nil), "pb.Outbound")
	proto.RegisterType((*ReportValueHeader)(nil), "pb.ReportValueHeader")
	proto.RegisterType((*ReportValueLines)(nil), "pb.ReportValueLines")
	proto.RegisterType((*ReportSalesHeader)(nil), "pb.ReportSalesHeader")
	proto.RegisterType((*ReportSalesLines)(nil), "pb.ReportSalesLines")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
	proto.RegisterType((*ResOnhandQTY)(nil), "pb.ResOnhandQTY")
	proto.RegisterType((*ResInbounds)(nil), "pb.ResInbounds")
	proto.RegisterType((*ResOutbounds)(nil), "pb.ResOutbounds")
	proto.RegisterType((*ResReportValue)(nil), "pb.ResReportValue")
	proto.RegisterType((*ResReportSalesHeader)(nil), "pb.ResReportSalesHeader")
	proto.RegisterType((*ParamDate)(nil), "pb.ParamDate")
}

func init() { proto.RegisterFile("module/pb/inventory.proto", fileDescriptor_62d3b5a39cf1533a) }

var fileDescriptor_62d3b5a39cf1533a = []byte{
	// 879 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x5d, 0x8e, 0xe3, 0x44,
	0x10, 0x4e, 0x9c, 0xff, 0xca, 0xec, 0x90, 0x6d, 0x0d, 0x2b, 0x33, 0x42, 0x10, 0x5a, 0x08, 0x0d,
	0x7f, 0xb3, 0x62, 0x79, 0xe4, 0x01, 0x84, 0x96, 0x0d, 0x2b, 0xad, 0x36, 0x59, 0x67, 0x04, 0xe2,
	0xb1, 0x13, 0xb7, 0x66, 0xcd, 0xd8, 0xdd, 0x1e, 0xbb, 0x1d, 0x94, 0x43, 0xc0, 0x25, 0x78, 0xe2,
	0x12, 0x5c, 0x80, 0x0b, 0x70, 0x9c, 0x55, 0x57, 0xb7, 0xed, 0x76, 0x9c, 0x3c, 0xcc, 0x9b, 0xab,
	0xaa, 0xfb, 0xeb, 0xaa, 0xef, 0xab, 0xaa, 0x04, 0x3e, 0x48, 0x64, 0x58, 0xc4, 0xfc, 0x69, 0xba,
	0x79, 0x1a, 0x89, 0x1d, 0x17, 0x4a, 0x66, 0xfb, 0xeb, 0x34, 0x93, 0x4a, 0x12, 0x2f, 0xdd, 0xd0,
	0x25, 0x4c, 0x96, 0xe2, 0x2d, 0x13, 0xe1, 0x9b, 0x9b, 0xdf, 0xc8, 0x0c, 0x7a, 0xf9, 0x5d, 0xe1,
	0x77, 0xe7, 0xdd, 0xab, 0x49, 0xa0, 0x3f, 0xc9, 0x25, 0x8c, 0x23, 0xc5, 0x13, 0xc1, 0x12, 0xee,
	0x7b, 0xe8, 0xae, 0x6c, 0x72, 0x01, 0x83, 0x5c, 0xc9, 0xed, 0x9d, 0xdf, 0x9b, 0x77, 0xaf, 0x7a,
	0x81, 0x31, 0xe8, 0x3f, 0x1e, 0x8c, 0x5e, 0x8a, 0x8d, 0x2c, 0x44, 0x48, 0x9e, 0xc0, 0x30, 0x95,
	0xcf, 0x99, 0xe2, 0x16, 0xd2, 0x5a, 0xe5, 0x3b, 0x5e, 0xfd, 0x0e, 0x9e, 0x7c, 0x15, 0x09, 0x6e,
	0xc1, 0xac, 0xa5, 0xdf, 0xb8, 0x57, 0xfb, 0x95, 0xf4, 0xfb, 0xe6, 0x0d, 0x34, 0xc8, 0x47, 0x00,
	0xf7, 0x6a, 0x1f, 0xf0, 0x2d, 0x8f, 0x76, 0xdc, 0x1f, 0x60, 0xc8, 0xf1, 0x90, 0x4f, 0xe1, 0x51,
	0x5a, 0x64, 0xdb, 0xb7, 0x2c, 0xe7, 0xab, 0x2c, 0xda, 0x72, 0x7f, 0x38, 0xef, 0x5e, 0x79, 0x41,
	0xd3, 0x49, 0xbe, 0x82, 0xc7, 0x4a, 0x2a, 0x16, 0xdb, 0x6c, 0xcd, 0xc9, 0x11, 0x9e, 0x6c, 0x07,
	0xc8, 0x1c, 0xa6, 0x77, 0x7f, 0x44, 0x8a, 0x89, 0x3c, 0x7a, 0x5d, 0x24, 0xfe, 0x18, 0x73, 0x77,
	0x5d, 0x3a, 0x57, 0x21, 0x15, 0x0f, 0xfd, 0x09, 0xc6, 0x8c, 0x51, 0x32, 0xf8, 0x5a, 0x33, 0x08,
	0x35, 0x83, 0xda, 0xa6, 0xff, 0x77, 0x61, 0xbc, 0x2c, 0x94, 0x21, 0xeb, 0x43, 0x98, 0xc8, 0x2c,
	0xe4, 0x99, 0xc3, 0x57, 0xed, 0x38, 0x42, 0x99, 0x2b, 0x4d, 0xef, 0x40, 0x9a, 0x27, 0x30, 0xbc,
	0x57, 0xfb, 0x65, 0xa1, 0x2c, 0x6f, 0xd6, 0x22, 0x14, 0xce, 0x72, 0x1e, 0xc7, 0x91, 0xb8, 0x35,
	0xd5, 0x0e, 0xb0, 0xda, 0x86, 0x8f, 0x5c, 0x03, 0xc1, 0xea, 0xcb, 0xc4, 0x5c, 0x06, 0x8f, 0x44,
	0xea, 0xb2, 0x47, 0x4e, 0xd9, 0xf4, 0xbf, 0x2e, 0x3c, 0x0e, 0x78, 0x2a, 0x33, 0xf5, 0x0b, 0x8b,
	0x0b, 0xfe, 0x33, 0x67, 0x21, 0xcf, 0x74, 0xce, 0x5b, 0x59, 0x08, 0xb5, 0xb6, 0x5d, 0xd6, 0x0b,
	0x2a, 0x5b, 0xc7, 0xf2, 0x22, 0x59, 0x63, 0x47, 0x79, 0x26, 0x56, 0xda, 0x5a, 0x70, 0x7c, 0x19,
	0xb1, 0xb0, 0x5a, 0x2f, 0x70, 0x3c, 0x9a, 0xbb, 0x34, 0x8b, 0x84, 0x42, 0xee, 0xfa, 0x86, 0xbb,
	0xca, 0x41, 0x7e, 0x80, 0x99, 0x93, 0x8a, 0xee, 0xab, 0xdc, 0x1f, 0xcc, 0x7b, 0x57, 0xd3, 0x67,
	0x17, 0xd7, 0xe9, 0xe6, 0xfa, 0x30, 0x16, 0xb4, 0x4e, 0xd3, 0x7f, 0xbb, 0x6d, 0x88, 0x07, 0x4e,
	0xcb, 0x1c, 0xa6, 0xf7, 0x6a, 0x7f, 0x63, 0xfa, 0x6a, 0x67, 0xdb, 0xdc, 0x75, 0x91, 0x2f, 0x60,
	0xc6, 0x76, 0xb7, 0xab, 0xac, 0x70, 0x1a, 0xb7, 0x8f, 0xa5, 0xb6, 0xfc, 0x95, 0x48, 0xab, 0x46,
	0x9b, 0x0f, 0x1c, 0x91, 0x1a, 0x11, 0xfa, 0xb7, 0x57, 0xca, 0xb1, 0x66, 0x31, 0xcf, 0xad, 0x1c,
	0x0d, 0xda, 0xba, 0x87, 0xb4, 0xe9, 0x28, 0xcb, 0x58, 0x82, 0x51, 0xcf, 0x46, 0x4b, 0x47, 0x25,
	0xc9, 0x32, 0xc9, 0xb9, 0x6a, 0x48, 0x82, 0x1e, 0xf2, 0x19, 0x9c, 0xa3, 0xf5, 0x8a, 0x6d, 0xd8,
	0x22, 0x93, 0x79, 0x6e, 0x6b, 0x39, 0xf0, 0x56, 0xe7, 0x56, 0x5c, 0xfc, 0x5e, 0xb0, 0x98, 0x09,
	0x3b, 0xcf, 0x07, 0x5e, 0xcd, 0x1f, 0x7a, 0x7e, 0x64, 0x19, 0x13, 0xb7, 0xd8, 0x8f, 0xbd, 0xc0,
	0x75, 0xd5, 0x32, 0x63, 0x89, 0x46, 0xe6, 0xd1, 0xa1, 0xcc, 0x75, 0x2c, 0x68, 0x9d, 0xa6, 0x7f,
	0x79, 0x6d, 0x08, 0x2d, 0x2a, 0x8e, 0xa1, 0x9e, 0x7a, 0xc3, 0x51, 0x65, 0x37, 0x67, 0xd6, 0x3b,
	0x31, 0xb3, 0xbd, 0x56, 0x83, 0xe0, 0x32, 0xe8, 0x37, 0x97, 0x81, 0x5d, 0x75, 0x6b, 0x69, 0xeb,
	0x37, 0x46, 0x6b, 0x62, 0x87, 0x47, 0x26, 0xb6, 0x94, 0xc2, 0xdd, 0x60, 0x8e, 0xa7, 0xbd, 0x0e,
	0xc7, 0xc7, 0xd6, 0x21, 0x81, 0x7e, 0xcc, 0x36, 0x0c, 0xb7, 0x97, 0x17, 0xe0, 0x37, 0x1d, 0xc1,
	0xe0, 0xa7, 0x24, 0x55, 0x7b, 0xba, 0x80, 0xb3, 0x80, 0xe7, 0xf5, 0x2f, 0xc5, 0x05, 0x0c, 0xf0,
	0x01, 0x3b, 0xc5, 0xc6, 0x20, 0x9f, 0x40, 0x3f, 0x64, 0x8a, 0xf9, 0x1e, 0xb2, 0xfe, 0x48, 0xb3,
	0x5e, 0x5d, 0x09, 0x30, 0x44, 0x9f, 0xc3, 0x34, 0xe0, 0xb9, 0xdd, 0xac, 0xf9, 0x09, 0x9c, 0x8f,
	0x1b, 0x38, 0x53, 0x8d, 0x63, 0x6f, 0x58, 0x94, 0x17, 0x26, 0x1d, 0xbb, 0x87, 0x4e, 0xc1, 0xcc,
	0x1b, 0x30, 0x67, 0x98, 0x8e, 0xbd, 0x62, 0x71, 0xde, 0xc0, 0x79, 0xc0, 0x73, 0x67, 0xb2, 0x4f,
	0x20, 0x7d, 0xde, 0x40, 0x7a, 0xff, 0x60, 0x6b, 0x98, 0x69, 0xb2, 0x90, 0xbf, 0xc2, 0x45, 0x05,
	0xe9, 0xce, 0xda, 0x03, 0x81, 0x9d, 0xab, 0x16, 0xf8, 0x7b, 0x98, 0xac, 0xaa, 0xe9, 0xbb, 0x84,
	0x71, 0xc8, 0x14, 0x7f, 0x91, 0xc9, 0xaa, 0x29, 0x4b, 0x5b, 0x2f, 0x7f, 0xfd, 0x7d, 0x23, 0x6d,
	0x47, 0x5a, 0xeb, 0xd9, 0x9f, 0x1e, 0xcc, 0x5e, 0x96, 0x7f, 0x01, 0xd6, 0x3c, 0xdb, 0x69, 0xd5,
	0xbf, 0x86, 0xb3, 0x05, 0x57, 0xb5, 0xb0, 0x13, 0x9d, 0x02, 0x6a, 0x7e, 0x39, 0x33, 0xd9, 0xd4,
	0xaa, 0xd3, 0x0e, 0xf9, 0x12, 0xa6, 0x0b, 0xae, 0x2a, 0xf9, 0x9c, 0xd3, 0xef, 0xd9, 0xd3, 0x65,
	0x8c, 0x76, 0x4a, 0xec, 0x4a, 0xa5, 0x63, 0xd8, 0x65, 0x90, 0x76, 0xc8, 0x37, 0x70, 0xbe, 0xe0,
	0xca, 0x15, 0xc3, 0xb9, 0x40, 0xec, 0x05, 0x27, 0x4c, 0x3b, 0xe4, 0x3b, 0xe7, 0x0a, 0x32, 0x46,
	0xb0, 0xe9, 0x2a, 0x9e, 0x2e, 0xfd, 0xc6, 0x35, 0x87, 0x54, 0xda, 0xd9, 0x0c, 0xf1, 0x5f, 0xd0,
	0xb7, 0xef, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x10, 0x46, 0xf3, 0x22, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InventoryServiceClient interface {
	GetOnhandQTY(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResOnhandQTY, error)
	GetInbounds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResInbounds, error)
	GetOutbounds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResOutbounds, error)
	GetReportValue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResReportValue, error)
	GetReportSales(ctx context.Context, in *ParamDate, opts ...grpc.CallOption) (*ResReportSalesHeader, error)
}

type inventoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewInventoryServiceClient(cc *grpc.ClientConn) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetOnhandQTY(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResOnhandQTY, error) {
	out := new(ResOnhandQTY)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/GetOnhandQTY", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetInbounds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResInbounds, error) {
	out := new(ResInbounds)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/GetInbounds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetOutbounds(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResOutbounds, error) {
	out := new(ResOutbounds)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/GetOutbounds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetReportValue(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ResReportValue, error) {
	out := new(ResReportValue)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/GetReportValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetReportSales(ctx context.Context, in *ParamDate, opts ...grpc.CallOption) (*ResReportSalesHeader, error) {
	out := new(ResReportSalesHeader)
	err := c.cc.Invoke(ctx, "/pb.InventoryService/GetReportSales", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
type InventoryServiceServer interface {
	GetOnhandQTY(context.Context, *Empty) (*ResOnhandQTY, error)
	GetInbounds(context.Context, *Empty) (*ResInbounds, error)
	GetOutbounds(context.Context, *Empty) (*ResOutbounds, error)
	GetReportValue(context.Context, *Empty) (*ResReportValue, error)
	GetReportSales(context.Context, *ParamDate) (*ResReportSalesHeader, error)
}

func RegisterInventoryServiceServer(s *grpc.Server, srv InventoryServiceServer) {
	s.RegisterService(&_InventoryService_serviceDesc, srv)
}

func _InventoryService_GetOnhandQTY_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetOnhandQTY(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/GetOnhandQTY",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetOnhandQTY(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetInbounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetInbounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/GetInbounds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetInbounds(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetOutbounds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetOutbounds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/GetOutbounds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetOutbounds(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetReportValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetReportValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/GetReportValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetReportValue(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetReportSales_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParamDate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetReportSales(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.InventoryService/GetReportSales",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetReportSales(ctx, req.(*ParamDate))
	}
	return interceptor(ctx, in, info, handler)
}

var _InventoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOnhandQTY",
			Handler:    _InventoryService_GetOnhandQTY_Handler,
		},
		{
			MethodName: "GetInbounds",
			Handler:    _InventoryService_GetInbounds_Handler,
		},
		{
			MethodName: "GetOutbounds",
			Handler:    _InventoryService_GetOutbounds_Handler,
		},
		{
			MethodName: "GetReportValue",
			Handler:    _InventoryService_GetReportValue_Handler,
		},
		{
			MethodName: "GetReportSales",
			Handler:    _InventoryService_GetReportSales_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "module/pb/inventory.proto",
}
